site_name: BoxHead Survivor Developer Docs
nav:
  - 主页: index.md
  - 开发日志:
    - DevLogs/test.md
  - 开发教程:
    - HowTos/2024-02-19-如何编辑开发者文档.md
  - 资源汇总:
    - Resources/test.md
  - 会议记录:
    - Meetings/test.md
  - 关于: about.md
theme: 
  name: material
  language: zh
  features:
    - navigation.tabs