site_name: BoxHead Survivor Developer Docs
nav:
  - 主页: index.md
  - 开发日志:
    - DevLogs/test.md
  - 开发教程:
    - HowTos/2024-02-19-如何编辑开发者文档.md
    - HowTos/2024-02-24-如何编辑Unity项目.md
  - 资源汇总:
    - Resources/2024-02-19-美术资源汇总.md
    - Resources/2024-02-24-肉鸽游戏参考汇总.md
    - Resources/2024-03-03-参考视频汇总.md
  - 会议记录:
    - Meetings/2024-02-19-2024年2-3月会议记录.md
  - 关于: about.md
theme: 
  name: material
  language: zh
  features:
    - navigation.tabs
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true